# Generated by Django 4.2.2 on 2023-06-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="external_id",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, unique=True
            ),
        ),
    ]
