# Generated by Django 4.2.2 on 2023-06-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_company_url_alter_company_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="url",
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
