# Generated by Django 4.2.2 on 2023-06-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0005_alter_news_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="external_id",
        ),
        migrations.AlterField(
            model_name="news",
            name="link",
            field=models.URLField(db_index=True, unique=True),
        ),
    ]
