# Generated by Django 4.2.2 on 2023-06-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0006_remove_news_external_id_alter_news_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="text",
            field=models.TextField(default="No text"),
        ),
    ]
