# Generated by Django 4.2.3 on 2023-07-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("description", models.TextField()),
                ("release_date", models.DateField()),
                ("connection_interface", models.CharField(max_length=150)),
                ("sensor_type", models.CharField(max_length=150)),
                ("sensor_resolution", models.IntegerField()),
                ("color", models.CharField(max_length=150)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
