# Generated by Django 4.2.3 on 2023-07-31 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mouse",
            name="color",
        ),
        migrations.RemoveField(
            model_name="mouse",
            name="connection_interface",
        ),
        migrations.RemoveField(
            model_name="mouse",
            name="sensor_resolution",
        ),
        migrations.AddField(
            model_name="mouse",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mouse",
            name="interface",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="mouse",
            name="length_radius",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="mouse",
            name="max_sensor_resolution",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="mouse",
            name="sensor_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
