# Generated by Django 4.2.3 on 2023-07-31 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_remove_mouse_color_remove_mouse_connection_interface_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mouse",
            old_name="length_radius",
            new_name="length_or_radius",
        ),
    ]
