# Generated by Django 4.2.3 on 2023-07-31 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_rename_length_radius_mouse_length_or_radius"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mouse",
            name="image",
            field=models.URLField(blank=True, db_index=True, null=True),
        ),
    ]
