# Generated by Django 4.2.3 on 2023-07-31 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_remove_mouse_interface_remove_mouse_length_or_radius_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mouse",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
