# Generated by Django 4.2.3 on 2023-07-31 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_mouse_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "product_type",
                    models.CharField(
                        blank=True,
                        choices=[("mouse", "Mouse"), ("keyboard", "Keyboard")],
                        null=True,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("description", models.TextField()),
                ("image", models.URLField(blank=True, db_index=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Mouse",
        ),
    ]
