# Generated by Django 4.2.3 on 2023-08-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_basket"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchase",
            name="is_completed",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
