# Generated by Django 4.2.3 on 2023-08-24 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("address", "0001_initial"),
        ("shop", "0013_purchase_finished_at_purchase_is_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="address",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchases",
                to="address.address",
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
