# Generated by Django 4.2.3 on 2023-08-24 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0005_alter_profile_photo"),
        ("shop", "0014_purchase_address_alter_purchase_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profiles",
                to="profile.profile",
            ),
        ),
    ]
