# Generated by Django 4.2.3 on 2023-08-25 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0006_alter_profile_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0015_purchase_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="profile",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profiles",
                to="profile.profile",
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="user",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
