# Generated by Django 4.2.2 on 2023-07-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Console",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("price_per_hour", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "price_per_month",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
            ],
        ),
    ]
