# Generated by Django 4.2.2 on 2023-07-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("console", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="console",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/console/"),
        ),
    ]
