# Generated by Django 4.2.2 on 2023-07-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("console", "0004_alter_console_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="console",
            name="name",
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
    ]
