# Generated by Django 4.2.2 on 2023-07-07 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("console", "0005_alter_console_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="console",
            old_name="price_per_hour",
            new_name="price_per_day",
        ),
        migrations.RemoveField(
            model_name="console",
            name="price_per_month",
        ),
    ]
