# Generated by Django 4.2.2 on 2023-07-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0002_room_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="src/apps/room/media/images/room"
            ),
        ),
    ]
