# Generated by Django 4.2.2 on 2023-07-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rent", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cluborder",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="cluborder",
            name="description",
        ),
        migrations.RemoveField(
            model_name="cluborder",
            name="user",
        ),
        migrations.RemoveField(
            model_name="consoleorder",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="consoleorder",
            name="description",
        ),
        migrations.RemoveField(
            model_name="consoleorder",
            name="user",
        ),
        migrations.RemoveField(
            model_name="roomorder",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="roomorder",
            name="description",
        ),
        migrations.RemoveField(
            model_name="roomorder",
            name="user",
        ),
        migrations.AddField(
            model_name="consoleorder",
            name="days",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
