# Generated by Django 4.2.2 on 2023-07-10 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rent", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cluborder",
            name="club",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="club_orders",
                to="rent.club",
            ),
        ),
        migrations.AlterField(
            model_name="cluborder",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="club_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="consoleorder",
            name="console",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="console_orders",
                to="rent.console",
            ),
        ),
        migrations.AlterField(
            model_name="consoleorder",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="console_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="roomorder",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="room_orders",
                to="rent.room",
            ),
        ),
        migrations.AlterField(
            model_name="roomorder",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="room_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
