# Generated by Django 4.2.2 on 2023-07-11 06:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rent", "0003_alter_cluborder_club_alter_cluborder_user_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ClubOrder",
            new_name="ClubRent",
        ),
        migrations.RenameModel(
            old_name="ConsoleOrder",
            new_name="ConsoleRent",
        ),
        migrations.RenameModel(
            old_name="RoomOrder",
            new_name="RoomRent",
        ),
    ]
