# Generated by Django 4.2.3 on 2023-07-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rent", "0008_alter_roomrent_room_alter_roomrent_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clubaddress",
            options={"verbose_name_plural": "Club addresses"},
        ),
        migrations.AlterField(
            model_name="consolerent",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="roomrent",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
    ]
