# Generated by Django 4.2.3 on 2023-07-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rent", "0010_clubrent_completed_date_clubrent_is_completed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomrent",
            name="hours",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="roomrent",
            name="people",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
