# Generated by Django 4.2.2 on 2023-07-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0002_club_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="src/apps/club/media/images/club"
            ),
        ),
    ]
