# Generated by Django 4.2.2 on 2023-06-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="gander",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                null=True,
            ),
        ),
    ]
