# Generated by Django 4.2.2 on 2023-06-17 11:53

from django.db import migrations, models
import src.apps.profile.validators


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0004_rename_gander_profile_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                validators=[src.apps.profile.validators.check_phone_number],
            ),
        ),
    ]
